name: create-release


on:
  workflow_dispatch:
    inputs:
      RELEASE_TYPE:
        type: choice
        options:
        - patch
        - minor
        - major
  pull_request:
    branches:
      - 'main'
    types:
      - closed


permissions:
  contents: write
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main

      - name: Release patch
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          token: ${{secrets.PAT}}
